contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true 
baseurl = "http://www.smohare.com"
canonifyurls = true
theme = "hugo-morphism"
title = "Shawn O'Hare"

[taxonomies]
  category = "categories" 
  group = "groups"
  series = "series"
  tag = "tags"

[params]
  subtitle = "Math, Data, Skepticism"
  copyrightHolder = "Shawn O'Hare"
  showPoweredBy = true

# -----------------------------------------------------------------------
# Morphism theme navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -100 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Categories"
  pre = "<i class='fa fa-tags fa-lg'></i> "
  weight = -90 
  identifier = "categories"
  url = "/categories"
[[menu.nav]]
  name = "Me"
  pre = "<i class='fa fa-user fa-lg'></i> "
  weight = -80
  identifier = "me"
  url = "/page/about/"

# -----------------------------------------------------------------------
# Morphism theme footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-github fa-2x'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com/shawnohare"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-twitter fa-2x'></i> "
  weight = -90 
  identifier = "twitter"
  url = "https://twitter.com/shawn_ohare"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-linkedin fa-2x'></i> "
  weight = -80 
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/shawnohare"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-envelope fa-2x'></i> "
  weight = -70 
  identifier = "mail"
  url = "mailto:ohare.shawn@gmail.com"
