contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://www.smohare.com"
theme = "hugo-morphism"
title = "Shawn O'Hare (.com)"
copyright = "© Shawn O’Hare.  <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\">Some rights reserved</a>."
editor = "nvim"
verbose = false
googleAnalytics = "UA-65318243-1"

[author]
  name = "Shawn O’Hare"
	uri = "https://plus.google.com/115904086044687543049"

[taxonomies]
  category = "categories"
  group = "groups"
  series = "series"
  tag = "tags"

[permalinks]
    post = "/:section/:year/:month/:filename/"

[params]
  subtitle = "Mathematicable Musings"
  showPoweredBy = true
  # listPaginatorLimit = 1000000

# -----------------------------------------------------------------------
# Morphism theme navigation menu
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "home"
  pre = ""
  weight = -110
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "posts"
  pre = ""
  weight = -100
  identifier = "posts"
  url = "/post"
# [[menu.nav]]
#   name = "categories"
#   pre = ""
#   weight = -90
#   identifier = "categories"
#   url = "/categories"
# [[menu.nav]]
#   name = "groups"
#   pre = ""
#   weight = -89
#   identifier = "groups"
#   url = "/groups"
# [[menu.nav]]
#   name = "me"
#   pre = ""
#   weight = -80
#   identifier = "me"
#   url = "/info/about/"

# -----------------------------------------------------------------------
# Morphism theme footer menu
# -----------------------------------------------------------------------
[[menu.footer]]
  name = "GitHub"
  pre = ""
  weight = -100
  identifier = "github"
  url = "https://github.com/shawnohare"
[[menu.footer]]
  name = "Twitter"
  pre = ""
  weight = -90
  identifier = "twitter"
  url = "https://twitter.com/shawn_ohare"
[[menu.footer]]
  name = "LinkedIn"
  pre = ""
  weight = -80
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/shawnohare"
[[menu.footer]]
  name = "Mail"
  pre = ""
  weight = -70
  identifier = "mail"
  url = "mailto:shawn@ohare.io"
